apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-2
  labels:
    app: demo-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-2
  template:
    metadata:
      labels:
        app: demo-2
    spec:
      containers:
        - name: demo-2
          image: cloudnatived/demo:hello
          ports:
          - containerPort: 9999
