apiVersion: v1
kind: Service
metadata:
  name: demo-2
  labels:
    app: demo-2
spec:
  # NOTE: depending on which version of the book you have, this may say port 9999. The latest version of the book uses 8888 to match the pod.
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: demo-2
  type: ClusterIP
